import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Precision Brew Espresso Machine',
    description: 'Brews professional-level espresso using smart pressure controls. Features an automatic milk frother, rapid thermoblock heater, and a brushed stainless steel chassis. Perfect for coffee enthusiasts looking to replicate their favorite local cafes.',
    price: 349.99,
    originalPrice: 399.99,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=600',
    stock: 12,
    sellerId: 'sell-alpha',
    sellerName: 'Alpha Tech Goods',
    rating: 4.8,
    ratingCount: 34,
    latitude: 37.7749, // San Francisco base coords
    longitude: -122.4194,
    verified: true,
    tags: ['espresso', 'coffee', 'smart-appliances'],
    originRegion: 'US',
    shippedGlobally: true
  },
  {
    id: 'prod-2',
    title: 'Artisanal Hand-Poured Soy Candle Set',
    description: 'A triad of natural, therapeutic-grade essential oil soy candles: Lavender Breeze, Cedar Forest, and Rosemary Mint. Poured in small batches with sustainable crackling wooden wicks and glass apothecary jars.',
    price: 24.50,
    category: 'Handcrafted',
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&q=80&w=600',
    stock: 45,
    sellerId: 'sell-beta',
    sellerName: 'Terra Crafts & Co',
    rating: 4.6,
    ratingCount: 18,
    latitude: 37.7833,
    longitude: -122.4167,
    verified: true,
    tags: ['candle', 'soy', 'aromatherapy'],
    originRegion: 'ZA',
    shippedGlobally: true
  },
  {
    id: 'prod-3',
    title: 'Heritage Sourdough Baker Kit',
    description: 'Get everything needed to start baking organic loaves. Includes a 50-year aged active local heritage sourdough starter, hand-woven proofing banneton, stainless steel dough bench knife, and matching cotton lame with brass blades.',
    price: 49.00,
    originalPrice: 59.99,
    category: 'Local Organic Food',
    imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&q=80&w=600',
    stock: 5,
    sellerId: 'sell-gamma',
    sellerName: 'Mission Yeast & Bakery',
    rating: 4.9,
    ratingCount: 52,
    latitude: 37.7699,
    longitude: -122.4468,
    verified: true,
    tags: ['sourdough', 'baking', 'organic'],
    originRegion: 'GB',
    shippedGlobally: true
  },
  {
    id: 'prod-4',
    title: 'Active Noise Cancelling Wireless Headphones',
    description: 'Hear nothing but your audio. Hybrid active noise filtering, premium memory-foam leather cups, up to 40 hours of continuous wireless playback under quick-charge mode, and a rugged foldable design.',
    price: 189.99,
    originalPrice: 249.99,
    category: 'Electronics',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600',
    stock: 8,
    sellerId: 'sell-alpha',
    sellerName: 'Alpha Tech Goods',
    rating: 4.4,
    ratingCount: 23,
    latitude: 37.7749,
    longitude: -122.4194,
    verified: true,
    tags: ['anc', 'headphones', 'wireless'],
    originRegion: 'US',
    shippedGlobally: true
  },
  {
    id: 'prod-5',
    title: 'Cold-Pressed California Honey (Single Source)',
    description: 'Raw, unpasteurized honey harvested from organic wildflower hives in Northern California. Light, rich aromatic floral profiles. Unbelievably rich in enzymatic properties and completely unfiltered.',
    price: 18.00,
    category: 'Local Organic Food',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600',
    stock: 50,
    sellerId: 'sell-gamma',
    sellerName: 'Mission Yeast & Bakery',
    rating: 4.7,
    ratingCount: 39,
    latitude: 37.7699,
    longitude: -122.4468,
    verified: true,
    tags: ['honey', 'organic', 'raw'],
    originRegion: 'JP',
    shippedGlobally: true
  },
  {
    id: 'prod-6',
    title: 'Minimalist Walnut Wood Laptop Elevator',
    description: 'Sustainably sourced black walnut elevator designed to reduce neck fatigue. Carved from solid hardwood in San Francisco, matching all contemporary desk aesthetics with slip-resistant silicone contact pads.',
    price: 68.00,
    category: 'Handcrafted',
    imageUrl: 'https://images.unsplash.com/photo-1527443195088-7da35f5bb7b5?auto=format&fit=crop&q=80&w=600',
    stock: 15,
    sellerId: 'sell-beta',
    sellerName: 'Terra Crafts & Co',
    rating: 4.5,
    ratingCount: 14,
    latitude: 37.7833,
    longitude: -122.4167,
    verified: true,
    tags: ['woodwork', 'walnut', 'laptop-dock'],
    originRegion: 'ZA',
    shippedGlobally: true
  }
];
